### ISSUE TITLE
Add "Authorization" header and "401 Unauthorized" response

### ISSUE THREAD

**Issue by dezlov** [almindor/lnet#1]
Add "Authorization" header and "401 Unauthorized" response to `lhttp` unit.

These are required to handle HTTP Authentication (Basic and Digest Access Authentication) in accordance with RFC 2617.

The responsibility for actually interpreting the "Authorization" header and requesting HTTP Authentication via "WWW-Authenticate" header is still with the user, which may later be implemented as a separate feature.

**Comment by dezlov** [comment]
A trivial patch has been uploaded to FPC bug tracker a while ago:
https://bugs.freepascal.org/view.php?id=31654

Alternatively, I can create a pull request in git, let me know.

**Comment by almindor** [comment]
Applied, thanks (forgot to close the issue before)
