### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by arminlinder** [almindor/lnet#18]
I tried to run the SMTPTest demo against my ISP mail server.

TLSMTPClient.EvaluateAnswer crashes with an invalid integer exception in the GetNum subroutine.

The server anwer (string Ans) is:

`'* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.'
`
GetNum tries to convert the first three letters to a number --> bang.

**Comment by trevoz** [comment]
Dovecot is an open-source IMAP and POP3 server for Unix-like operating systems - it is not an SMTP server! That explains your result.

**Comment by almindor** [comment]
> Dovecot is an open-source IMAP and POP3 server for Unix-like operating systems - it is not an SMTP server! That explains your result.

thanks :)
