### ISSUE TITLE
Question: Purpose of Self:= nil in lwebserver.pp

### ISSUE THREAD

**Issue by zamronypj** [almindor/lnet#23]
@almindor 

In file `lnet/lib/lwebserver.pp` line 655, there is line

```
  Self := nil;
  tempStr := TLHTTPServer(lServerSocket.Creator).ServerSoftware;
  if Length(tempStr) > 0 then
    AddEnvironment('SERVER_SOFTWARE', tempStr);

  AddEnvironment('GATEWAY_INTERFACE', 'CGI/1.1'); 
...
```

Why `Self` is set to nil? This causes AddEnvironment() call to fail because `Self` variable now nil.

**Comment by almindor** [comment]
o.O I have no idea. IIRC this code was done by `@mischi` from the `#fpc` irc channels. Seems like a bug to me.
