### ISSUE TITLE
LNET doesn't work for latest distribution with OPENSSL 1.1.1

### ISSUE THREAD

**Issue by han-k59** [almindor/lnet#4]
LNET worked fine for me several years. However it doesn't work for me in the latest Linux distributions (Lubuntu 19.04 and Xubuntu). It raises an exception in LnetSSL: 

**Unable to initialize OpenSSL library, please check your OpenSSL installation**

 See:
https://forum.lazarus.freepascal.org/index.php/topic,46527.0.html

**Comment by han-k59** [comment]
Problem is solved by a newer openssl.pp then the one provide by FPC 3.2

**Comment by almindor** [comment]
Hmm I see so the `OpenSSL.pp` provided by version 3 of FPC is outdated?

**Comment by han-k59** [comment]
At the moment Lnet didn't work for me with either FP3.2.0 or FPC 3.3.1 under Lubuntu 19.04. Only the openSSL.pp provided by user Tz did fix the problem. Incompatibility or something else, I can only guess. Hopefully user Tz can explain the difference.

p.s. Is it not better to increase the version name number 0.66 after the 2019 patches? My first impression was that nothing had changed after reading the Readme.

**Comment by almindor** [comment]
lNet has been mostly in maintenance mode in the last ~8 years or so. I can
make a github release with a version bump once this issue is solved. I
wonder if the problem is FPC's openssl being too old.

st 28. 8. 2019 o 7:21 han-k59 <notifications@github.com> napísal(a):

**Comment by almindor** [comment]
Can you try removing the

```
  {$ifndef VER3}
  lOpenSSL,
  {$else}
  OpenSSL,
  {$endif}
```

inside `lnetssl.pp` and changing it to directly use `OpenSSL` to see if it
fixes the issue? If I understand correctly you fixed the issue by replacing
`lOpenSSL.pas` inside the lib dir, correct?

st 28. 8. 2019 o 9:48 Ales Katona <almindor@gmail.com> napísal(a):

**Comment by han-k59** [comment]
The LopenSSL is grayed out. If I move the cursor above uses OpenSSL; the hint indicates the original fpc/packages/openssl/src/openssl.pp. As soon I place the new openSSL.pp in the Lib directory of Lnet, the cursor hint indicates Lnet/lib/openSSL.pp  Then it works. 

So it doesn't work with fpc/packages/openssl/src/openssl.pp

**Comment by han-k59** [comment]
Attached the two versions of OpenSSL from FPC3.2 and the one I got from Tz. I will try to make an comparison extract.
[openssl.zip](https://github.com/almindor/lnet/files/3551976/openssl.zip)

**Comment by han-k59** [comment]
Here is a comparison of the code:
https://www.diffchecker.com/kPEmnXTX

**Comment by han-k59** [comment]
With the included OpenSSL version it is working. This can be closed
