### ISSUE TITLE
TZSeconds() in lCommon.pp returns the wrong sign on Windows

### ISSUE THREAD

**Issue by Doooc** [almindor/lnet#9]
TZSeconds() incorrectly returns a negative number for a +GMT timezone on Windows, because of Windows.GetTimeZoneInformation() returning the opposite sign to baseunix.TZSeconds()).

This causes GMTToLocalTime() and LocalTimeToGMT() to be wrong on Windows, subtracting the offset instead of adding, and vice versa.

So in TZSeconds(), line 212 of lCommon.pp should be changed to:
`Result := -lInfo.Bias * 60`

**Comment by almindor** [comment]
I've been off lNet development for ages. Would it be possible for you to please make a PR? I'll try it out as soon as I'm able and merge it in.

NOTE: please make sure to gate this for windows only if it's a windows hack. I'll have to check this out closer.

**Comment by Doooc** [comment]
Thanks, pull request made.
